'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TBK_FA_System.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property closeLotsummary() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("closeLotsummary", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdmindetailadjustNC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdmindetailadjustNC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdmindetailadjustNC1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdmindetailadjustNC1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdmindetailNC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdmindetailNC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdmindetailNC1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdmindetailNC1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdmindetailNC2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdmindetailNC2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdmindetailNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdmindetailNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdmindetailselectadjustNC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdmindetailselectadjustNC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdmindetailselectadjustNC1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdmindetailselectadjustNC1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdminnumpadadjust() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdminnumpadadjust", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdminnumpadregister() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdminnumpadregister", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdminnumpadregister1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdminnumpadregister1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdminnumpadregister2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdminnumpadregister2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdminregister() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdminregister", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdminregister1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdminregister1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdminsearchNC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdminsearchNC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdminsearchNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdminsearchNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdminselectcodeNC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdminselectcodeNC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdminselectcodeNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdminselectcodeNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdminselecttypeNC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdminselecttypeNC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdminselecttypeNC1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdminselecttypeNC1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAdminselecttypeNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAdminselecttypeNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAlertsure() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAlertsure", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAlertsure1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAlertsure1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectAlertupdate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectAlertupdate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectDetailnc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectDetailnc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectDetailnc1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectDetailnc1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectDetailnc2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectDetailnc2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectHome() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectHome", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectHome1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectHome1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectHome11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectHome11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectHome2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectHome2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectHome3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectHome3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectHome4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectHome4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectHome5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectHome5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectHome6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectHome6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectNumpadadjust() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectNumpadadjust", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectNumpadregister() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectNumpadregister", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectRegister() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectRegister", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectRegister1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectRegister1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectRegister2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectRegister2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectSelectcode() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectSelectcode", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property defectSelecttype() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("defectSelecttype", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Information() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Information", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Information1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Information1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Information2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Information2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property inst_qty() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inst_qty", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property inst_qty2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inst_qty2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property loginAdmin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loginAdmin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property loginAdmin1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loginAdmin1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MainMenu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MainMenu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property menuLogin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menuLogin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
